packageName: elasticsearch-operator

targetNamespace: openshift-operators

source: redhat-operators

sourceNamespace: openshift-marketplace

channel: stable-5.8

# not used, included to use by shell script
operatorName: elasticsearch-operator